# Generated by Django 5.2.1 on 2025-05-20 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureddestination',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_destinations', to='core.listing'),
        ),
    ]
